# Application
spring.application.name=speech-to-text-backend
server.port=8081

# Database - will properly configure on Day 2
spring.datasource.url=jdbc:postgresql://localhost:5432/sttdb
spring.datasource.username=postgres
spring.datasource.password=mentixora123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT
jwt.secret=mySecretKeyForSpeechToTextApp2024SuperLongString
jwt.expiration=86400000
assemblyai.api.key=0b83d86013a646ff9179ca9d9a4720c9
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG